### ISSUE TITLE
Nav bar and structur

### ISSUE THREAD

**Issue by jhibbeard89** [danielpippin/FASTCOU#2]
### Todo
- [ ] Add navbar from the [Kitt](https://uikit.lewagon.com/)
- [ ] Add routes to sign in and sign up
- [ ] Add container around yield in application.html.erb

### Figma
<img width="484" alt="Screenshot 2023-03-08 at 13 59 46" src="https://user-images.githubusercontent.com/5392107/223719608-1c49981c-9635-43e9-b761-3981e55eee55.png">
